input_data_path: "data/raw/train.csv"
save_model_path: "models/lr_default.pkl"

columns_params:
  target: "is_canceled"

train_params:
  penalty: "l2"
  solver: "lbfgs"
  max_iter: 100

splitting_params:
  test_size: 0.1
  random_state: 42
